theme: jekyll-theme-slate
title: Machine Learning: Predicting MLB's Hall of Fame selections at 2020
description: CS7641 Project 27 - Jaewon Lee, Jonghoon Won, Jongseuk Woo, Kuchul Jung, Seunghyup Han
