theme: jekyll-theme-slate
title: Predicting MLB Hall of Famer by machine learning approach
subtitle: I new it :)
description: CS7641 Project 27 - Jaewon Lee, Jonghoon Won, Jongseuk Woo, Kuchul Jung, Seunghyup Han
